Repository datarobot-oss/cli, pull requests merged in 2025-08, with the labels that each got.

#22 [CFX-3285] Handle existing directory when cloning repository
  cmd/templates/clone/cmd.go
  cmd/templates/clone/model.go
Labels: 00 - Ready for Review

#24 [CFX-3417] Pretty up the "you can close this page"
  cmd/auth/auth.go
  cmd/templates/setup/loginModel.go
  internal/assets/assets.go
  internal/assets/templates/success.html
Labels: 00 - Ready for Review, Auto Merge when Ready

#26 [CFX-3405] TUI Testing Framework
  .gitignore
  cmd/auth/auth.go
  cmd/auth/login.go
  cmd/auth/logout.go
  cmd/auth/setURL.go
  cmd/dotenv/cmd.go
  cmd/templates/setup/loginModel.go
  cmd/templates/setup/loginModel_test.go
  cmd/templates/setup/model.go
  go.mod
  go.sum
  internal/config/auth.go
  internal/config/constants.go
Labels: 00 - Ask for Review on Green
